### PR TITLE
Don't let #retrieve_work to short-circuit when there are no queues to handle. Fix #63

### LINKED ISSUE #63: CPU Issue
sidekiq-limit_fetch 3.0.1 (with sidekiq 4) is throwing my CPU into overdrive - to 105%.

sidekiq 4 without sidekiq-limit_fetch doesn't do this, and sidekiq 3 with sidekiq-limit_fetch 2.4.2 works fine as well. It's only 4 + limit_fetch.

I'm running El Capitan. Let me know if there is anything I can test for you to help with this. I love this gem! Thanks

### PR DESCRIPTION
**Pull request by 907th**
BIG thanks to @d4rky-pl and @grahamlyons!

### CODE REVIEW

**Comment by 907th** [comment]
Only `jruby` build is failing. I'm not sure why.

**Comment by 907th** [comment]
It seems like a bug with `jruby-head` builds on `travis-ci`
[The issue](https://github.com/travis-ci/travis-ci/issues/5861)

**Comment by brainopia** [comment]
Thank you very much! :smile:

**Comment by d4rky-pl** [comment]
Glad I could help!

**Pull request merged**
