### PR TITLE
Support Sidekiq edge and ruby2.3.0

### PR DESCRIPTION
**Pull request by alpaca-tc**
- Fixed specs. Change `UnitOfWork` attribute name. `message` -> `job`
- Remove deprecated method. `Thread.exclusive` -> `Mutex#synchronize`

### CODE REVIEW

**Comment by flingbob** [comment]
:+1:

**Comment by kirs** [comment]
Thanks! It made my day.

**Comment by j133y** [comment]
:+1: Thanks!

**Comment by onesupercoder** [comment]
Thanks!

**Comment by krzysiek1507** [comment]
:+1: @brainopia

**Comment by rosenfeld** [comment]
:+1:

**Comment by larryzhao** [comment]
:+1: Great Fix.

Really looking forward to get the new version of it.

**Comment by brainopia** [comment]
Thank you! Sorry for delay :bow: 
I've released a new version of gem: 3.1

**Pull request merged**
