### PR TITLE
add pause_for to lock a queue for a limited amount of time

### PR DESCRIPTION
**Pull request by MartinNowak**

### CODE REVIEW

**Comment by MartinNowak** [comment]
I want to use this to throttle processing of the queue.
You think that will work?

**Comment by brainopia** [comment]
Thanks a lot, yes, sounds like it should work.
Probe count shouldn't be affected by pause so it's ok.

**Comment by MartinNowak** [comment]
> Thanks a lot, yes, sounds like it should work.

It does a really nice job allowing to evenly distribute a batch of jobs over a few days, by adding `Sidekiq::Queue[:queuename].pause_for_ms 7.days * 1000 / number_of_jobs` at the top of the worker perform method.

**Comment by brainopia** [comment]
Nice example, thanks!

**Pull request merged**
